### ISSUE TITLE
how is rgbif working?

### ISSUE THREAD

**Issue by sckott** [CIAT-DAPA/cwr_occurrencesvalidation#6]
I noticed in https://github.com/CIAT-DAPA/cwr_occurrencesvalidation/blob/master/RScripts/GBIF_batch_download.R that you're using `rgbif` 

Not to pry, but how has it been using the package? I am the maintainer, so if you have any pain points, do let me know if there's anything I can fix or make better

feel free to close this whenever

**Comment by npcastaneda** [comment]
Hi Scott, 

The R routine I put in our github account is a draft of the code I used for downloading large batches of data from GBIF, I still need to organize and clean further the code so it is useful for other users. I was in direct contact with you when I was trying to automatize this process, and I am very grateful for all the help and support you provided.

Kind regards, 

Nora

**Comment by sckott** [comment]
Ah! I had forgotten, sorry about that. Anyway, glad it's useful
